### ISSUE TITLE
Restore hotel block booking link to homepage

### ISSUE THREAD

**Issue by tim-schilling** [djangocon/2023.djangocon.us#109]
With the theme update the link was changed to point directly to the convention center. I imagine we want to point people to our room block link otherwise folks are only going to find rooms at $500+ per night.

The link is: https://www.marriott.com/events/start.mi?id=1674740649947&key=GRP

**Comment by jefftriplett** [comment]
@tim-schilling I found two links and replaced them (both homepages). Let me know if we missed one.
