### ISSUE TITLE
Add PR template to the repository to remind people to apply blog label

### ISSUE THREAD

**Issue by tim-schilling** [djangocon/2023.djangocon.us#125]
https://github.com/djangocon/2023.djangocon.us/pull/124 finalized some work to automatically announce that a new blog post has been published on the communications channel is slack if the pull request has the "blog" label assigned to it (at the time of deployment).

It would be helpful to future folks to have a pull request template that reminds them if they're publishing a blog post to attach that label. 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by AfiMaameDufie** [comment]
Hi @tim-schilling ,
I'd to pick this up.

**Comment by tim-schilling** [comment]
Sounds good, thank you @AfiMaameDufie!

**Comment by tim-schilling** [comment]
Closed in #128
