### ISSUE TITLE
An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.

### ISSUE THREAD

**Issue by emmakodes** [djangocon/2023.djangocon.us#13]
Getting above error when run "bundle install"

**Comment by emmakodes** [comment]
I use wsl on windows. Currently, I have switched to using windows and I have setup on windows.

**Comment by drewbrew** [comment]
It seems to have worked for me using Ubuntu 22.04 (jammy) on WSL2 on Windows 11:

```bash
sudo apt install ruby-bundler
bundle config set --local path vendor/bundle
bundle install
bundle exec jekyll serve
```

**Comment by emmakodes** [comment]
Okay, nice. I use Ubuntu 22.04 (Jammy) wsl2 on windows 10. I will try the above command and give feedback

**Comment by emmakodes** [comment]
Thanks, bro, the command worked for windows 10 wsl2 Ubuntu 22.04(jammy)

sudo apt install ruby-bundler
bundle config set --local path vendor/bundle
bundle install
bundle exec jekyll serve

**Comment by drewbrew** [comment]
Sweet, glad it worked out for you!
