### ISSUE TITLE
Mastodon handles in speaker profile

### ISSUE THREAD

**Issue by drewbrew** [djangocon/2023.djangocon.us#134]
In 2022, we had speakers upload their mastodon handles in the form `https://example.social/@username`. 

In 2023, about half the speakers who added their mastodon handle did it in the form `@user@example.social`.

We need a way to programmatically convert the latter to the former, either at import time or in the template code

**Comment by drewbrew** [comment]
CC @mtrythall and @jefftriplett for ideas

**Comment by jefftriplett** [comment]
If you are looking for a tech solution, that should be possible to do here: https://github.com/djangocon/2023.djangocon.us/blob/main/bin/process.py#L113-L122

My buddy ChatGPT recommends:

```python
def convert_handle(handle):
    if not handle.startswith("@"):
        return handle

    username, domain = handle[1:].split("@")
    return f"https://{domain}/@{username}"
```

...Which I think would work. Should we try it on https://github.com/djangocon/2023.djangocon.us/pull/135?

**Comment by drewbrew** [comment]
Looks right to me.
