### ISSUE TITLE
Update logo to 2023 and launch our blog

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2023.djangocon.us#44]
We need a place to post announcements and the biggest blemish is our logo showing 2022 instead of 2023.

**Comment by jalakoo** [comment]
Which logo file needs updating?

**Comment by jefftriplett** [comment]
@jalakoo our 2022 logo.svg file. 🙏

**Comment by jefftriplett** [comment]
https://github.com/djangocon/2023.djangocon.us/blob/main/static/img/logo.svg and https://github.com/djangocon/2023.djangocon.us/blob/main/static/img/logo-2022.svg

**Comment by jefftriplett** [comment]
@jalakoo @sodevious thank you both for helping out. Much appreciated. 

Closed in #49
