### ISSUE TITLE
Landing page's reference to last year's schedule is pointed at 2021

### ISSUE THREAD

**Issue by tim-schilling** [djangocon/2023.djangocon.us#57]
The link for "See last year's schedule" is pointed at https://2021.djangocon.us/talks. It should be https://2022.djangocon.us/talks

**Comment by TerroR75** [comment]
Hey, I would like to take this issue :)

**Comment by TerroR75** [comment]
Sent pull request, tried to find anything else that needed a change as well. Let me know if its everything
